### ISSUE TITLE
Add a calculator program on python language.

### ISSUE THREAD

**Issue by akkupy** [akkupy/Code_Dump#197]

**Comment by SRUJANA2199** [comment]
hi could you assign me this issue under hacktoberfest23 ?

**Comment by policeakshithreddy** [comment]
Upload a static portfolio website on web folder.

**Comment by nancy-singh10** [comment]
hey 
plz assign me this issue under hacktoberfest2023 
thanks

**Comment by Neel-07** [comment]
hello @akkupy  can you assign me this issue
