### ISSUE TITLE
Implement Rock, Scissors, Paper Game Logic in Python

### ISSUE THREAD

**Issue by Petsamuel** [akkupy/Code_Dump#203]
The goal of this task is to create the core logic for the Rock, Scissors, Paper game in Python. This includes handling user input, generating computer choices, determining the winner, and displaying the results.

**Comment by sdehury34** [comment]
Hi please assign this task to me. I will be able to this.

**Comment by Petsamuel** [comment]
But I created this issue? Why was it not assigned to me?
