### ISSUE TITLE
Implement Fibonacci Series Function in Python

### ISSUE THREAD

**Issue by Petsamuel** [akkupy/Code_Dump#204]
The goal of this task is to create a Python function that generates the Fibonacci series up to a specified number of terms or a maximum value.

**Comment by Petsamuel** [comment]
I'ld like to work on this

**Comment by Shreshth-Srivastava** [comment]
Hello there, I have solved this issue and I am now creating a pull request regarding this.

**Comment by akkupy** [comment]
U were not assigned ... Request it first...

I'm adding u to this issue anyway...Create a PR refering this issu

**Comment by nancy-singh10** [comment]
hey 
plz assign me this issue under hacktoberfest2023 
thanks

**Comment by Petsamuel** [comment]
@Shreshth-Srivastava you assigned this issue to me first... 
I have solved it and was waiting for october 1st to make a PR..
people can't just come from no where and clam other peoples task

**Comment by Petsamuel** [comment]
![image](https://github.com/akkupy/Code_Dump/assets/65086865/e938de3b-975a-49e6-bc55-bfd93ef1e8c2)
other are holding off theirs PR as well so it would count.

**Comment by akkupy** [comment]
@Petsamuel I'm just holding all the PRs until Oct 1.

I'll merge your PR first on this issue.
