### ISSUE TITLE
Add data structure programs using python langauge on the data_structure folder.

### ISSUE THREAD

**Issue by akkupy** [akkupy/Code_Dump#206]
The Goal of this task is to add some DSA programs using python language on the 'data_structure' folder.

**Comment by SyntaxSmiler03** [comment]
Hello @akkupy, 
Could you please assign this issue to me? I would like to work on it.

**Comment by SyntaxSmiler03** [comment]
under hacktober fest 2023

**Comment by nancy-singh10** [comment]
hey 
plz assign me this issue under hacktoberfest2023 
thanks

**Comment by IndranjanaChatterjee** [comment]
Hii ,
I would like to work on this issue under hacktobarfest23.
Can u pls assign it to me?

**Comment by akkupy** [comment]
@IndranjanaChatterjee  State the DSA you are implementing..too

**Comment by IndranjanaChatterjee** [comment]
@akkupy I would like to add Double_Linked List in C

**Comment by akkupy** [comment]
@IndranjanaChatterjee Go ahead!

**Comment by IndranjanaChatterjee** [comment]
Thanks

**Comment by Samihan15** [comment]
hey i would like to work on this issue can you please assign it to me ?

**Comment by IndranjanaChatterjee** [comment]
@akkupy I have created a PR under #267 for the Double Linked-list problem in python in the data_structure folder
