### ISSUE TITLE
Constructor Overloading in Java Implementation

### ISSUE THREAD

**Issue by akkupy** [akkupy/Code_Dump#213]
Write a Java program to calculate the perimeter of different shapes namely circle and rectangle using the concept of constructor overloading.

**Comment by Aniket3063** [comment]
hello could you assign me this issue under hacktoberfest23 ?

**Comment by IndranjanaChatterjee** [comment]
Hello ,I would like to work on this. Can you assign it to me under hacktoberfest23?

**Comment by IndranjanaChatterjee** [comment]
Thanks
