### ISSUE TITLE
Implement Threads in Java

### ISSUE THREAD

**Issue by akkupy** [akkupy/Code_Dump#214]
Write a Java program that implements a multi-threaded program which has three threads. First thread generates a random integer every 1 second. If the value is even, second thread computes the square of the number and prints. If the value is odd the third thread will print the value of cube of the number.

**Comment by Aniket3063** [comment]
Hi @akkupy, I got the problem and would like to work on this. can you assign me this?

**Comment by SadeeshaJayaweera** [comment]
@akkupy i have the solutions for this as i already worked on this for my college tutorials. please do assign me to this task as well. Thanks
