### ISSUE TITLE
Downward Triangle Pattern in Python

### ISSUE THREAD

**Issue by akkupy** [akkupy/Code_Dump#216]
* * * * * * * * * * * 
                   * * * * * * * * * * 
                    * * * * * * * * * 
                     * * * * * * * * 
                      * * * * * * * 
                       * * * * * * 
                        * * * * * 
                         * * * * 
                          * * * 
                           * * 
                            *

Display this pattern , take rows as input.

**Comment by SyntaxSmiler03** [comment]
Can you please assign it to me? I would like to solve this

**Comment by Shreshth-Srivastava** [comment]
Hello there, I have solved this issue, so may I create a pull request submitting my solution ?

**Comment by akkupy** [comment]
Create a PR refering #216

**Comment by Shreshth-Srivastava** [comment]
Okay

**Comment by IndranjanaChatterjee** [comment]
I would like to solve this problem. Please assign this to me

**Comment by IndranjanaChatterjee** [comment]
Thanks

**Comment by IndranjanaChatterjee** [comment]
@akkupy Completed the required downward Triangle pattern problem in python under #291 .
