### ISSUE TITLE
Add (CPP) : Longest Palindromic Substring Problem (DSA)

### ISSUE THREAD

**Issue by YashkShrivas4491** [akkupy/Code_Dump#220]
Given a string str, the task is to find the longest substring which is a palindrome.

Examples:
Input: str = “babba” 
Output: “abba”

could you assign me this issue @akkupy

**Comment by akkupy** [comment]
I have assigned u..Happy Coding !

**Comment by nancy-singh10** [comment]
hey 
plz assign me this issue under hacktoberfest2023 
thanks

**Comment by nancy-singh10** [comment]
plz assign me under hacktober2023

**Comment by YashkShrivas4491** [comment]
> plz assign me under hacktober2023

As you can see I already assigned so why are you asking again ,
If you want to contribute open an issue then solve
