### ISSUE TITLE
Implement Pascal's Triangle Generation in Python

### ISSUE THREAD

**Issue by Petsamuel** [akkupy/Code_Dump#224]
Pascal's Triangle is a mathematical structure where each number is the sum of the two numbers directly above it. The first few rows of Pascal's Triangle look like this:
       ![image](https://github.com/akkupy/Code_Dump/assets/65086865/c544f6fd-df42-4153-949c-183a86b18883)

**Comment by TFM-HITESH** [comment]
Hey ! Can I be assigned to this issue ? I have decent knowledge in the language and can implement it fairly quickly. I would like to make a PR for this as a coding submission for the upcoming Hacktoberfest 23. 

Thank you for your time ! Have a nice day !

**Comment by A-y-ush** [comment]
Hi , I would like to work on this issue , can I be assigned to it ?

**Comment by MishraTanishq619** [comment]
Hey! I would like to work on this issue.
Plz assign this task to me.
I would like to make a PR which would addup in Hacktoberfest.

Thank you. Have a nice Day.
