### ISSUE TITLE
Tower of Hanoi in Java

### ISSUE THREAD

**Issue by IndranjanaChatterjee** [akkupy/Code_Dump#226]
Tower of Hanoi is such a problem that involves moving a stack of disks from one peg to another following certain rules:
Rules are as follows:
1.Only one disk can be moved at a time
2.Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack. In other words, a disk can only be moved if it is the uppermost disk on a stack.
3.No larger disk may be placed on top of a smaller disk.

**Comment by tanay-nagde** [comment]
hey @akkupy could you assign me this issue under hacktoberfest2023

**Comment by Rasayan** [comment]
Hey @akkupy could you assign me this issue for Hacktoberfest2023

**Comment by Abhinavagarwa** [comment]
hey @akkupy could you please assign me this issue under Hacktober2023

**Comment by IndranjanaChatterjee** [comment]
@akkupy  created a new PR under #270 for the Tower of Hanoi problem in java.
