### ISSUE TITLE
sudoku_solver in cpp

### ISSUE THREAD

**Issue by nancy-singh10** [akkupy/Code_Dump#227]
plz assign me under hacktober2023

**Comment by akkupy** [comment]
Elaborate on which language you are using?

**Comment by nancy-singh10** [comment]
using cpp

**Comment by akkupy** [comment]
place it on cpp folder

**Comment by nancy-singh10** [comment]
ok thanks

i will send PR on 1 under hacktoberfest2023

**Comment by Tejoooo** [comment]
Heyy I am interested in this work can u assign me to this issue

**Comment by 457ayan** [comment]
hey i am intrested for contribution this code please assign

**Comment by iKoNFlair** [comment]
Can you please assign me to contribute and implement the  Sudoku Solver
