### ISSUE TITLE
Implement Fibonacci series program in python 

### ISSUE THREAD

**Issue by mohit-dhote** [akkupy/Code_Dump#292]
Goal is to implement a DSA program in python language and place it in the data_structure folder.

**Comment by Anuragpal010104** [comment]
@mohit-dhote Can you please assign this issue to me under HACTOBERFEST

**Comment by mohit-dhote** [comment]
I have added the file @akkupy please merge the PR.

**Comment by akkupy** [comment]
I have merged all PRs that met the guidelines.
