### ISSUE TITLE
Update the Exisitng README into a Stylish and Informative README 

### ISSUE THREAD

**Issue by akkupy** [akkupy/Code_Dump#324]
* Try to add Step by step instructions for newbies to make their first PR
* Try adding Pictures .
* Make it more stylish.

**Comment by the-amazing-atharva** [comment]
@akkupy I would like to work on this issue for hacktoberfest!

I have experience in making README.md so I can update this one too

**Comment by akkupy** [comment]
@the-amazing-atharva Go ahead!

**Comment by vermaaarti** [comment]
@akkupy would like to make it more interactive as well as attractive.

**Comment by akkupy** [comment]
@vermaaarti Go ahead
