### ISSUE TITLE
N-Queens Java solution code in Java Folder

### ISSUE THREAD

**Issue by Adijainy** [akkupy/Code_Dump#331]
- The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.
- Given an integer n, return all distinct solutions to the n-queens puzzle.
- Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space, respectively.

**Comment by akkupy** [comment]
Link this issue while creating the PR

**Comment by Adijainy** [comment]
how do i link?
