### ISSUE TITLE
Letter Combinations of a Phone Number in Java in LeetCode Folder

### ISSUE THREAD

**Issue by Adijainy** [akkupy/Code_Dump#367]
Problem no. - 17
Link - https://leetcode.com/problems/letter-combinations-of-a-phone-number/description/
Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.
A mapping of digits to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.

**Comment by neharathig** [comment]
Can you assign this to me?

**Comment by Adijainy** [comment]
You can open issue and the authors will assign you the issues

**Comment by neharathig** [comment]
ok, thanks
