### ISSUE TITLE
roman to integer 

### ISSUE THREAD

**Issue by tarun4632** [akkupy/Code_Dump#472]
https://leetcode.com/problems/roman-to-integer/ 
i want to solve this leet code problem can u please assign it to me under the hactober fest @akkupy

**Comment by usmanbvp** [comment]
I wish to solve this problem assign this to me under hacktoberfest 2023

**Comment by akkupy** [comment]
@usmanbvp Create another issue

**Comment by khushisaxena17** [comment]
assign it to me under hacktoberfest please!
