### ISSUE TITLE
Add Data in the Content Section of README.md

### ISSUE THREAD

**Issue by akkupy** [akkupy/Code_Dump#507]
Task is to review all the folders present in this repo and update the 'content' table in the README.md filen with necessary information.

* Cover which type of programs are present in each folder.
* Try to  have a link to every folder within the Contents  table.

**Comment by AMANMUHAL** [comment]
assign this to me ,, i would try incorporating all the changes

**Comment by shubhankar132** [comment]
Kindlly assign this issue to me.

**Comment by akkupy** [comment]
@AMANMUHAL Try to make the changes within 23:00 IST else @shubhankar132 will be assigned

**Comment by AMANMUHAL** [comment]
@akkupy Done ,, please review the PR
